name = "rendahl"
uuid = "41c54a58-7f14-46c8-a170-251cabdb430a"
authors = ["Hariharan Jayashankar"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
